language: julia
julia:
 - 0.6
before_script:
 - julia -e 'Pkg.add("StaticArrays")'
after_success:
 - julia -e 'cd(Pkg.dir("Hop")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
 - julia -e 'Pkg.add("Documenter")'
 - sudo pip install mkdocs-material
 - julia -e 'cd(Pkg.dir("Hop")); include(joinpath("docs", "make.jl"))'
