language: julia
julia:
 - 1.0
after_success:
 - julia -e 'using Pkg; cd(Pkg.dir("Hop")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
 - julia -e 'Pkg.add("Documenter")'
 - sudo pip install mkdocs-material pygments
 - julia -e 'cd(Pkg.dir("Hop")); include(joinpath("docs", "make.jl"))'
